### ISSUE TITLE
(all?) Interfaces get reported as unused

### ISSUE THREAD

**Issue by jcward** [back2dos/ctl#5]
Simple test that shows that a (used) interface gets reported as unused:

```
package;

class Main {
  public static function main() {
    trace('Hey, I\'m some project!');
    var u = new SomeClass();
    u.greet();
  }
}

class SomeClass implements IUsedInterface {
  public function new() {
    trace('Hi, I\'m a used class');
  }

  public function greet() trace("Oh, hi!");
}

interface IUsedInterface {
  public function greet():Void;
}
```

Macro output:
```
Partially Dead Types:

  IUsedInterface @ src/Main.hx:19

    greet @ src/Main.hx:20
```

**Comment by back2dos** [comment]
This is actually correct, because you're not using the interface. You would be in this case:

```haxe
var u:IUsedInterface = new SomeClass();
```

Assume there were another implementor of `IUsedInterface`. You wouldn't want its `greet` method kept, just because another implementor's `greet` method is kept due to direct usage.

In some sense, what this is telling you is that you have an abstraction, that you're not using. It's up to you how to deal with it ;)

**Comment by jcward** [comment]
Ah, so "implementing the interface" is not the usage we're talking about... It's actual referencing of the IUsedInterface type. Fair enough. I suppose I could wish for reporting on both states -- "interface never implemented" and "interface type never used" -- but it's not high on my priority list. I think, if I get to using this significantly, that the latter (implemented, but not referenced) may just go on my "ignore" list. That is to say, I guess I don't mind ignoring if a dev specifies `IQuack`, but as of today, only `class Duck` implements `IQuack`, so `IQuack` itself is never referenced. :laughing:

**Comment by back2dos** [comment]
Let me give you some unsolicited advise :D

Judging from our own code base, I would say that this is indeed an indicator of cargo cultism. It gives programmers a nice and cozy feeling to follow the "best practice" of "using interfaces". But if this warning shows up, it's time to wonder whether the value (and cost) of using interfaces is properly understood.

The advantage of writing your code against an `IQuack` is that calling code can supply *anything* that quacks. This is an immensely powerful [design principle](https://en.wikipedia.org/wiki/Dependency_inversion_principle). The disadvantage is that you can't just jump to the implementation, because the whole point was to fully decouple the code that's calling it from the code that's providing it. Like almost all things in programming it's a trade-off, that should be carefully considered. Perhaps programming should be called trade-off-weighing. Then hopefully it would less often be understood as digging-yourself-into-a-hole-by-following-best-practices-blindly.

Going back to the topic itself: the compiler must detect which fields on an interface are ever used **through the interface** in order to keep them on all implementors (that are not fully eliminated). If it finds that some fields are not used on the interface, there are the following options:

- ignore it, as you suggested
- remove them from the interface - [smaller interfaces are better](https://en.wikipedia.org/wiki/Interface_segregation_principle)
- call them through the interface, rather than through the implementation - increase indirection and thereby flexibility
